#!/bin/sh
set -eu

APP_NAME_DEFAULT="Chill Codex"
BUNDLE_ID="io.github.cpiz.chill-codex"
EXECUTABLE_NAME="chill-codex-launcher"
ICON_NAME="chill-codex.icns"
MARKER_NAME="chill-codex.generated"
REDUCED_MOTION_FLAG="--force-prefers-reduced-motion"

usage() {
  cat <<'USAGE'
Usage: sh install.sh [options]

Create a macOS launcher app that starts Codex with reduced motion.

Options:
  --codex-app PATH     Path to Codex.app. Default: /Applications/Codex.app
  --install-dir DIR    Directory for the generated app. Default: ~/Applications
  --app-name NAME      Generated app name. Default: Chill Codex
  --help              Show this help message.

Environment variables:
  CODEX_APP_PATH
  CHILL_CODEX_INSTALL_DIR
  CHILL_CODEX_APP_NAME
USAGE
}

log() {
  printf '%s\n' "$1"
}

die() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

require_macos() {
  os_name="$(uname -s)"
  if [ "$os_name" != "Darwin" ]; then
    die "Chill Codex only works on macOS."
  fi
}

strip_trailing_slash() {
  value=$1
  while [ "${value%/}" != "$value" ]; do
    value=${value%/}
  done
  printf '%s' "$value"
}

xml_escape() {
  printf '%s' "$1" | sed \
    -e 's/&/\&amp;/g' \
    -e 's/</\&lt;/g' \
    -e 's/>/\&gt;/g'
}

shell_quote() {
  printf "'"
  printf '%s' "$1" | sed "s/'/'\\\\''/g"
  printf "'"
}

plist_icon_name() {
  plist_path=$1
  if command -v /usr/libexec/PlistBuddy >/dev/null 2>&1; then
    /usr/libexec/PlistBuddy -c 'Print :CFBundleIconFile' "$plist_path" 2>/dev/null || true
  fi
}

copy_codex_icon() {
  codex_app=$1
  resources_dir=$2
  plist_path="$codex_app/Contents/Info.plist"
  codex_resources="$codex_app/Contents/Resources"
  icon_from_plist="$(plist_icon_name "$plist_path")"

  for candidate in "$icon_from_plist" "${icon_from_plist}.icns" "electron.icns" "icon.icns" "Codex.icns"; do
    [ -n "$candidate" ] || continue
    icon_path="$codex_resources/$candidate"
    if [ -f "$icon_path" ]; then
      cp "$icon_path" "$resources_dir/$ICON_NAME"
      return 0
    fi
  done

  return 1
}

write_info_plist() {
  plist_path=$1
  app_name=$2
  app_name_escaped="$(xml_escape "$app_name")"

  cat >"$plist_path" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleDisplayName</key>
  <string>$app_name_escaped</string>
  <key>CFBundleExecutable</key>
  <string>$EXECUTABLE_NAME</string>
  <key>CFBundleIconFile</key>
  <string>chill-codex</string>
  <key>CFBundleIdentifier</key>
  <string>$BUNDLE_ID</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>$app_name_escaped</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>1.0.0</string>
  <key>CFBundleVersion</key>
  <string>1</string>
  <key>LSMinimumSystemVersion</key>
  <string>12.0</string>
  <key>NSHighResolutionCapable</key>
  <true/>
</dict>
</plist>
PLIST
}

write_launcher() {
  launcher_path=$1
  codex_app=$2
  codex_app_literal="$(shell_quote "$codex_app")"

  cat >"$launcher_path" <<LAUNCHER
#!/bin/sh
# Generated by chill-codex. Edit install.sh in the project instead.
set -eu

CODEX_APP_DEFAULT=$codex_app_literal
CODEX_APP=\${CODEX_APP_PATH:-\$CODEX_APP_DEFAULT}
REDUCED_MOTION_FLAG="$REDUCED_MOTION_FLAG"

if [ ! -d "\$CODEX_APP" ]; then
  /usr/bin/osascript -e 'display alert "Chill Codex" message "Codex.app was not found. Set CODEX_APP_PATH or reinstall Chill Codex with --codex-app."' >/dev/null 2>&1 || true
  exit 1
fi

exec /usr/bin/open -na "\$CODEX_APP" --args "\$REDUCED_MOTION_FLAG"
LAUNCHER

  chmod 755 "$launcher_path"
}

CODEX_APP="${CODEX_APP_PATH:-/Applications/Codex.app}"
INSTALL_DIR="${CHILL_CODEX_INSTALL_DIR:-$HOME/Applications}"
APP_NAME="${CHILL_CODEX_APP_NAME:-$APP_NAME_DEFAULT}"

while [ $# -gt 0 ]; do
  case "$1" in
    --codex-app)
      [ $# -ge 2 ] || die "--codex-app requires a path."
      CODEX_APP=$2
      shift 2
      ;;
    --install-dir)
      [ $# -ge 2 ] || die "--install-dir requires a directory."
      INSTALL_DIR=$2
      shift 2
      ;;
    --app-name)
      [ $# -ge 2 ] || die "--app-name requires a name."
      APP_NAME=$2
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      die "Unknown option: $1"
      ;;
  esac
done

require_macos

CODEX_APP="$(strip_trailing_slash "$CODEX_APP")"
INSTALL_DIR="$(strip_trailing_slash "$INSTALL_DIR")"
WRAPPER_APP="$INSTALL_DIR/$APP_NAME.app"
CONTENTS_DIR="$WRAPPER_APP/Contents"
MACOS_DIR="$CONTENTS_DIR/MacOS"
RESOURCES_DIR="$CONTENTS_DIR/Resources"
LAUNCHER_PATH="$MACOS_DIR/$EXECUTABLE_NAME"
MARKER_PATH="$RESOURCES_DIR/$MARKER_NAME"

[ -d "$CODEX_APP" ] || die "Codex.app not found at $CODEX_APP"
[ -f "$CODEX_APP/Contents/Info.plist" ] || die "$CODEX_APP does not look like a macOS app bundle."

if [ -e "$WRAPPER_APP" ] && [ ! -f "$MARKER_PATH" ]; then
  die "$WRAPPER_APP already exists and was not created by chill-codex. Remove it or choose --app-name."
fi

mkdir -p "$MACOS_DIR" "$RESOURCES_DIR"
write_info_plist "$CONTENTS_DIR/Info.plist" "$APP_NAME"
write_launcher "$LAUNCHER_PATH" "$CODEX_APP"
printf '%s\n' "generated-by=chill-codex" >"$MARKER_PATH"

if copy_codex_icon "$CODEX_APP" "$RESOURCES_DIR"; then
  :
else
  log "Warning: Codex icon was not found. The launcher will use a generic app icon."
fi

if command -v /usr/bin/touch >/dev/null 2>&1; then
  /usr/bin/touch "$WRAPPER_APP"
fi

log "Installed: $WRAPPER_APP"
log ""
log "Next steps:"
log "  1. Quit Codex if it is already running."
log "  2. Open $APP_NAME from $INSTALL_DIR."
log "  3. Keep it in the Dock if you want this to be your default launcher."
